### ISSUE TITLE
Bias correction by the {R-Hyfo} Delta method

### ISSUE THREAD

**Issue by jasmineacampos** [Yuanchao-Xu/hyfo#10]
Hello, 
I am trying to perform the {R-Hyfo} bias correction of total monthly precipitation data from the ETA-HadGEM2-ES, ETA-Miroc5 and ENSEMBLE regionalized climate models, based on specialized observed data called “Xavier” (DOI: 10.1002/joc.4518).

However, when I run the code below, I get the following error:
Error in biasCorrect_core(frcData[lon, lat, ], hindcastData[lon, lat, : This method needs frc data to have the same length as obs data.

The same data used in the correction with the Delta method did not obtain errors when used for the correction with the EQM, GQM, SCALING methods; and I can't identify what is wrong.

My question is: Can this method only correct the bias if they have the same number of data for observations and frc? Also, is the default method 'delta' (Fig. 1) or 'scaling' (Fig. 2)?

Fig 1 https://github.com/Yuanchao-Xu/manuals/blob/master/hyfo.Rmd (Line 783)
Fig 2 https://cran.r-project.org/web/packages/hyfo/hyfo.pdf     (Page 7)

I am sending below my code and data. Could you please check it?
[Data.zip](https://github.com/Yuanchao-Xu/hyfo/files/8467112/Data.zip)

Figure 1
![Fig1](https://user-images.githubusercontent.com/103450092/162814260-5439ae3c-62a7-44fd-8090-dd251bc0a9e4.jpg)
Figure 2
![Fig2](https://user-images.githubusercontent.com/103450092/162814264-388dfc7c-75ab-4e70-b06b-a6a7d7428a4f.jpg)

Thanks.

My code:

#------------------------------------                      Script          -------------------------------------------------------
V.select.month <- c("JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC")

for(i in 1:12) { # Main loop is initiated

  #---------------------- Selection for each month
  #1980 - 2000
  Prec_hist_1980_2000_Xavier <- hyfo::loadNcdf(filePath="./Prec_monthly_historical_Xavier_1980-2000.nc", varname="Precipitation", year = 1980:2000, month = i)  
  Prec_hist_1980_2000_HadGEM2 <- hyfo::loadNcdf(filePath="./Prec_monthly_historical_ETA-HadGEM2-ES_1980-2000_Doce.nc", varname="Precipitation", year = 1980:2000, month = i)  
  Prec_hist_1980_2000_MIROC <- hyfo::loadNcdf(filePath="./Prec_monthly_historical_ETA-Miroc5_1980-2000_Doce.nc", varname="Precipitation", year = 1980:2000, month = i)  
  Prec_hist_1980_2000_ENSEMBLE <- hyfo::loadNcdf(filePath="./Prec_monthly_historical_ENSEMBLE_1980-2000_Doce.nc", varname="Precipitation", year = 1980:2000, month = i)    
  
  #2001 - 2005
  #Prec_hist_2001_2005_Xavier <- hyfo::loadNcdf(filePath= "./Prec_monthly_historical_Xavier_2001-2005.nc", varname="Precipitation", year = 2001:2005, month = i)   
  Prec_hist_2001_2005_HadGEM2 <- hyfo::loadNcdf(filePath="./Prec_monthly_historical_ETA-HadGEM2-ES_2001-2005_Doce.nc", varname="Precipitation", year = 2001:2005, month = i)   
  Prec_hist_2001_2005_MIROC <- hyfo::loadNcdf(filePath="./Prec_monthly_historical_ETA-Miroc5_2001-2005_Doce.nc", varname="Precipitation", year = 2001:2005, month = i)  
  Prec_hist_2001_2005_ENSEMBLE <- hyfo::loadNcdf(filePath= "./Prec_monthly_historical_ENSEMBLE_2001-2005_Doce.nc", varname="Precipitation", year = 2001:2005, month = i)  
  
  #---------------------- Correction
    # Delta biasCorrect {hyfo} is used to bias-correct the input timeseries hyfo dataset for the period 2001 a 2005
  HadGEM2_2001_2005.DELTA.BC <- hyfo::biasCorrect(obs = Prec_hist_1980_2000_Xavier, hindcast = Prec_hist_1980_2000_HadGEM2, frc = Prec_hist_2001_2005_HadGEM2, method = 'delta', preci = TRUE) 
  MIROC_2001_2005.DELTA.BC <- hyfo::biasCorrect(obs = Prec_hist_1980_2000_Xavier, hindcast = Prec_hist_1980_2000_MIROC, frc = Prec_hist_2001_2005_MIROC, method = 'delta', preci = TRUE)
  ENSEMBLE_2001_2005.DELTA.BC <- hyfo::biasCorrect(obs = Prec_hist_1980_2000_Xavier, hindcast = Prec_hist_1980_2000_ENSEMBLE, frc = Prec_hist_2001_2005_ENSEMBLE, method = 'delta', preci = TRUE)
  
   #---------------------- Export
  #DELTA writeNcdf {hyfo} is used write raster objects to netCDF files for the period 2001 a 2005
  writeNcdf(gridData=HadGEM2_2001_2005.DELTA.BC,filePath=paste0("HadGEM2_2001_2005_DELTA_BC_",V.select.month[i],".nc"))
  writeNcdf(gridData=MIROC_2001_2005.DELTA.BC,filePath=paste0("MIROC_2001_2005_DELTA_BC_",V.select.month[i],".nc"))
  writeNcdf(gridData=ENSEMBLE_2001_2005.DELTA.BC,filePath=paste0("ENSEMBLE_2001_2005_DELTA_BC_",V.select.month[i],".nc"))
  
} #Main loop is closed

#END OF CODE

**Comment by Yuanchao-Xu** [comment]
Hi @jasmineacampos ,

Thanks.
Regarding your questions:
1. Yes, for Delta method needs frc and obs due to the algorithm, the bias correction is based on obs data, so obs and frc needs to be the same length.
![image](https://user-images.githubusercontent.com/12883455/162863734-25140d15-dcf1-4856-884e-ad34a61530a3.png)

2. The default method is scaling, the manual is a little outdated. The package function help page is the only reference.
![image](https://user-images.githubusercontent.com/12883455/162865241-009e1c90-9d9e-4fd8-b50f-5692780ac4d9.png)
