### ISSUE TITLE
First Column is not date or wrong format

### ISSUE THREAD

**Issue by afifatalukder** [Yuanchao-Xu/hyfo#11]
Hello there, 
I want to bais correct some data, my codes are following
new_data <- biasCorrect(ban_tas ,hindcast = ban_his, ban_obs, method="eqm") 
But showing the following error 

Error in biasCorrect.TS(frc, hindcast, obs, method, scaleType, preci, :
First column is not date or Wrong Date formate, check the format in ?as.Date{base}
and use as.Date to convert.If your input is a hyfo dataset, put input = "hyfo" as an
argument, check help for more info.

I have formated date to %Y-%m-%d and I also used as.Date function as instructed, but still showing the same error. 
looking forward for your kind response.

**Comment by Yuanchao-Xu** [comment]
Hi @afifatalukder, have you check the format after you use as.Date? is it exactly the same format as the example shows?

**Comment by afifatalukder** [comment]
@Yuanchao-Xu 
Sir, I have checked multiple times. Date formate is year-month-day after using as.Date function. 
Thank you.

**Comment by Yuanchao-Xu** [comment]
Hi @afifatalukder, pls type in `?biasCorrect` and see the examples in the manual. Your data is not exactly the same as the sample timeseries shows. Please adjust accordingly, to make your data exactly the same format as the sample data.

**Comment by afifatalukder** [comment]
@Yuanchao-Xu 
Got it. Thank you so much, Sir.
