### ISSUE TITLE
"Hyfo" Package and Bias Correction

### ISSUE THREAD

**Issue by Cloverclimate** [Yuanchao-Xu/hyfo#12]
Hello,  
 
I have been trying to use the package “hyfo” for bias correction for my research project.
 

My research project aims to calculate drought projections for Scotland for the future using CMIP6 ensemble models. For this, I am trying to bias correct my CMIP6 climate model data using observational ERA5 datasets.  
 
I have followed all the rules as outlined in the document but my code is not working and returns an error as follows : 
 
Error in (function (classes, fdef, mtable)  :  
  unable to find an inherited method for function ‘biasCorrect’ for signature ‘"RasterStackTS", "RasterStackTS", "RasterStackTS"’ 
 
I realise that there is something within my data that the function is not able to work with, hence the error, but I cannot figure out what it is.  

 I have attached a copy of my script (the part that covers the problem) and example data files that can be used to run the code.  

If you can help me out, it will be immensely helpful ! 

Precipitation data attached : 
1.	->historical climate model data 
2.	-> forecast climate model data 
3.	-> ERA5 observational dataset for the baseline period of study (1980-2010)

1.  [pr_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412_v20181126 2.nc](https://durhamuniversity-my.sharepoint.com/:u:/g/personal/lbvq64_durham_ac_uk/EWjd-qDegbFJmbFqQLpPpJQBMMny2Pg4QH6V4hcH4KBVfA)
2.  [pr_Amon_BCC-CSM2-MR_ssp126_r1i1p1f1_gn_201501-210012_v20190314.nc](https://durhamuniversity-my.sharepoint.com/:u:/g/personal/lbvq64_durham_ac_uk/EZdkikWWLFpOsv7MqSWvHV0BviPEMDBy4YqhbC9w7Ewwjw)
3.  [adaptor.mars.internal-1664806420.6580343-32648-12-01f0b7b0-a9fd-4fb3-b056-a49d9b5aa230 1.nc](https://durhamuniversity-my.sharepoint.com/:u:/g/personal/lbvq64_durham_ac_uk/ERyoWGqql65OncWZO4JIcIMBtQXaSU9LAVTpCVTgC84WFg)

**Comment by Yuanchao-Xu** [comment]
Hi @Cloverclimate , you may try the solution [here](https://stackoverflow.com/a/53124958) first.
try to specify which function from which package you are using.

**Comment by Cloverclimate** [comment]
Unfortunately, that did not work. I keep getting the same error. My best guess is that there is some problem with the way the data is formatted that the functions are not recognising, but I do not know how to format the input data or understand what is wrong. I do not really know how to program in R. I only know how to work with pre-exisiting code that can be used for climate data analysis, so I am struggling

**Comment by Yuanchao-Xu** [comment]
@Cloverclimate hi, can you highlight in which step you have the error?

**Comment by Cloverclimate** [comment]
The exact step where I have the error: 

FIRST_ssp126_ppt_bcc_csm <- biasCorrect(first_ssp126_ppt_bcc_csm, baseline_ppt_bcc_csm, baseline_ppt_era5, method ="eqm", preci = TRUE, prThreshold = 1, extrapolate ="no")

Input data : 
first_ssp126_ppt_bcc_csm = time series data of monthly gridded precipitation data (forecast data by climate model - 2023-2030)
baseline_ppt_bcc_csm = time series data of monthly gridded precipitation data (hindcast data by climate model - 1980-2010)
baseline_ppt_era5 = time series of monthly gridded precipitation data (observational data - 1980-2010). 

FIRST_ssp126_ppt_bcc_csm = aiming this to be the bias corrected forecast data returned for 2023-2030.

**Comment by Yuanchao-Xu** [comment]
@Cloverclimate Hihi, saw u use brick to load ncdf files, actually in hyfo there is a loadNCDF function to do load ncfd, can you try that function to make sure it's aligned within hyfo environment, and see if there are still errors. Have you read the manual provided for biascorrect? http://docs.wixstatic.com/ugd/199c69_f3c30d4625a545908b5c0f13e17f0b33.pdf
