### ISSUE TITLE
Error in Loading .nc file in HYfO package in loadNCDF function?

### ISSUE THREAD

**Issue by lodhajyoti** [Yuanchao-Xu/hyfo#5]
Hi
  I have attached a sample file in which  I am getting the following error:
>filePath <- system.file("extdata", "tasmax_WAS-44_ECMWF-ERAINT_evaluation_r1i1p1_IITM-RegCM4-4_v5_day_19790101-19801231.nc", package = "hyfo")
>varname <- getNcdfVar(filePath)   
> ev <- loadNcdf(filePath, varname)
Error in loadNcdf(filePath, varname) : 
  Your file has less than 3 dimensions.

As my data contain three dimensions in it. 
Wait for a reply.

**Comment by lodhajyoti** [comment]
Hi 
Link for the sample data file "https://drive.google.com/open?id=1H3tfZFhMfRoiJy63oZiBPK7W_es-54sr"

**Comment by Yuanchao-Xu** [comment]
@lodhajyoti 

Hi, by using getNcdVar, you will obtain 3 variable names, of which I think you need the "tasmax". Use "tasmax" instead of varname when loadNcdf, since varname is not a string but a vector.

**Comment by lodhajyoti** [comment]
Hi
 Thanks it solved my issue.I have three issue which as follows
1)How  I can change the units in writeNcdf function as it is only for time units, how to give units like K for (kelvin) or C (Celsius) in our data sets.
2) How to set missing values as NA as it is taking NAN in the data sets?
3) Which is the best method for Temperature? As currently  I am using qunatile mapping EQM , Is it correct ?.
Wait for a positive reply.

**Comment by Yuanchao-Xu** [comment]
@lodhajyoti 

Hi, 
for Q1 and Q2, it's about dataframe in R, and can be simply achieved by adding one columns in R, or replacing values in R. By googling it, I think you can find a better solution.

For Q3, please type in `?biasCorrect` in R and check the documentation about different bias correction method.

**Comment by Mulugetat** [comment]
I can install getNcdfVar. I get the following message:
install.packages("getNcdfVar")
Installing package into ‘C:/Users/pc/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘getNcdfVar’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
What can you please help me?

**Comment by Yuanchao-Xu** [comment]
Hi @Mulugetat, I've no idea of the package "getNcdfVar", maybe you can try to contact the author of that package?

**Comment by Mulugetat** [comment]
Thanks, Dear @Yuanchao-Xu. I went to the installation of this package after trying to read the variable name from NC climate data file this way:
                     > varname <- getNcdfVar(filePath)
but I'm getting this error:
                      Error in getNcdfVar(filePath) : could not find function "getNcdfVar"
My basic problem is this.

**Comment by Yuanchao-Xu** [comment]
Hi @Mulugetat try library(hyfo) first, then run the code above.

**Comment by Mulugetat** [comment]
Thanks, @Yuanchao-Xu. 
It worked for me after loading the following 3 packages: library(hyfo), library(ncdf4) and library(R.utils)..

**Comment by Mulugetat** [comment]
I am planning to use hyfo for CMIP6 data in ncdf format. I followed the following steps as per the hyfo downscaling example:
> library(hyfo)
> library(ncdf4)
> library(R.utils)
> filePath <- system.file("extdata", "D:/CMIP6/Copernicus_EU/Precipitation/Historical/NC files/pr.nc", package = "hyfo")

but I'm getting the following error message for
> varname <- getNcdfVar(filePath)
Error in nc_open(filePath) : 
  Passed a filename that is NOT a string of characters!

Would please help me in spotting the possible source of this error? 

Thanks,

**Comment by Yuanchao-Xu** [comment]
@Mulugetat please follow instructions by `??getNcdfVar`. 
![image](https://user-images.githubusercontent.com/12883455/168217832-bab672b4-6c9c-4bda-88e5-82427cacc128.png)
then print out the filePath, and compare it with yours.
That may give you some idea.
