### ISSUE TITLE
Gridding a time series with Package Hyfo

### ISSUE THREAD

**Issue by CristoFacundoP** [Yuanchao-Xu/hyfo#6]
Dear Yuanchao,

I have a daily time series of precipitation, which I intend to transform it into a single NetCDF file of daily precipitation. So, first, I would like to explore the best way to impute missing values, grid the daily values of the different available weather stations and get daily raster files into a .nc format. I have learned about the Package "hyfo" and I think I can do it through it. However, I am experiencing some issues, and thus I haven't found a straightforward way to do it.
 
My database contains id, date, cod, lon, lat, elev, and precipitation value of 41 climate stations for the period 1980-2018. I have NAs values in the database. I organised the dataset following the hyfo Easy Start, so the first column presents date and the other 50 columns present a climate station, while rows present the values/NAs [14245 observations of 42 variables], as shown in the image below. The location of the stations [long, lat, elev, cod] is kept in a different file. 
![image](https://user-images.githubusercontent.com/41880180/64790538-e0093f80-d53b-11e9-80a7-79c46465a304.png)

The annual precipitation values and NA values per each station look like this:

![image](https://user-images.githubusercontent.com/41880180/64791369-3dea5700-d53d-11e9-9a8f-a52b9d7ffdc3.png)

Since I have missing values, I attempted to use the 'FillGap' function, but I got the following error message: "**Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) :  0 (non-NA) cases**" what I understand is that some stations with missing values are making noise so the function gets the error. Not so sure whether or not deleting those station would allow me to fill gaps with that function because I already deleted others. I am also not so sure that a method based on the correlation between neighbouring stations is the best approach to fill data gaps as the stations are located at a very irregular relieve. **So my first question is what might be wrong when filling gaps? There might be a better function?**

On the other hand, I learned that Package hyfo presents functions to read, analyse and write raster and NetCDF forms. However, I do not find a way out to grid the daily time series and get the .nc file. **I would appreciate any input, idea or suggestion**.

Thank you,

Sincerely,

**Comment by Yuanchao-Xu** [comment]
Hi @CristoFacundoP


Pleas check [here ](https://github.com/Yuanchao-Xu/hyfo/blob/master/R/fillGap.R) the documentation for `fillGap`

Basically it's based on the idea that rainfall within a certain area is similar, so a implicit precondition is that the stations should be close to each other, at least within a same basin. My suggestion is that split your 41 stations into groups with similar climate characteristics.

Second, the methodology is based on the correlation of stations. For your case, there is a huge period of time that all the stations have NA values, which is impossible to do correlations. My suggestion is that remove those periods, and anyway they are meaningless. Or, if NA means 0 in your case, you can replace NA with 0.
