### ISSUE TITLE
Error in loadNcdf(filePath, varname) :    Your file has less than 3 dimensions.

### ISSUE THREAD

**Issue by pradhancda** [Yuanchao-Xu/hyfo#8]
Sir,

Please help to fix this problem.

> filePath <- system.file("extdata", "uas20062050rcp45concat-cdo.nc", package = "hyfo")
> uas <- getNcdfVar(filePath)
> nc <- loadNcdf(filePath, uas)
Error in loadNcdf(filePath, uas) : Your file has less than 3 dimensions.

regards,
Subhasis

**Comment by Yuanchao-Xu** [comment]
As the message shows, your file has less than 3 dimensions...
For a qualified nc file, at least you should have 3 dimensions (lon, lat,
value).

**Comment by pradhancda** [comment]
Sir,

After giving this code
> nc <- loadNcdf(filePath, "uas")

problem solved.

Thank you Sir.
for your early response

But, i have one more question to get clarified.
Sir, you have used tgriddata as observed. 
can i use another .nc file ( era5) as observed.
If so, how can be ??



regards,
Subhasis

**Comment by Yuanchao-Xu** [comment]
@pradhancda yes you can use any file as observed, when you do biascorrection, just replace the obs with your own observed data.

**Comment by pradhancda** [comment]
Sir,

Is it Ok ?

file1 <- system.file("extdata", "uas20062050rcp45concat-cdo.nc", package = "hyfo")
uas <- getNcdfVar(file1)    
mod <- loadNcdf(filePath, "uas")

file2 <- system.file("extdata", "u10-20062019era5.nc", package = "hyfo")
u10 <- getNcdfVar(file2)    
obs <- loadNcdf(filePath, "u10")

biasFactor <- getBiasFactor(mod, obs, method = 'eqm', extrapolate = 'constant',
                            preci = TRUE)
newFrc <- applyBiasFactor(mod, biasFactor, obs = obs)


Please Suggest.....

**Comment by Yuanchao-Xu** [comment]
@pradhancda seems ok, please check here a more detailed instruction. http://docs.wixstatic.com/ugd/199c69_f3c30d4625a545908b5c0f13e17f0b33.pdf

**Comment by pradhancda** [comment]
Sir, 

Again, I got this Error
 biasFactor <- getBiasFactor(mod, obs)
Error in obsData[lon, lat, ] : incorrect number of dimensions

**Comment by Yuanchao-Xu** [comment]
@pradhancda go through the instructions above first using examples, then if there are still problems, you can str(your data) to compare differences between your data and the data from the example.

**Comment by pradhancda** [comment]
Sir, 
 
Please help  to short out these points....

How can I prepare tgridData from any netcdf ?
Can I merge all netcdf ?
How the newfrc will be saved in a netcdf ?


regards,
Subhasis
