### ISSUE TITLE
First Column Wrong Date Format

### ISSUE THREAD

**Issue by isamarcortes** [Yuanchao-Xu/hyfo#9]
Hi,

I am trying to bias correct for time series data and I get this error:
Error in biasCorrect.TS(frc, hindcast, obs, method, scaleType, preci,  : 
  First column is not date or Wrong Date formate, check the format in ?as.Date{base} 
         and use as.Date to convert.If your input is a hyfo dataset, put input = "hyfo" as an
         argument, check help for more info.

This is the line of code I am using to bias correct:
PREQM26 <- biasCorrect(forecastP26 ,hindcast = hindcastP26, TRMM_DF,method="eqm")

where forecastP26 is my forecast data, hindcastP26 is my hindcast data and TRMM_DF is my observed data. I double check that each one of these dataframes does have the first column as the date and use the as.Date function to convert the first column to the correct date per the instructions of the error. After all of that, I still have received the same error. Any and all feedback on this issue is greatly appreciated!

**Comment by Yuanchao-Xu** [comment]
Hi,

There are examples showing what is a correct date format, here
<https://yuanchao-xu.github.io/hyfo/> in the user manual.
If your date format is exactly the same as the examples, and the error
still comes out. Please send me some sample data.

Yuanchao

**Comment by aldotapia** [comment]
I got the same error and I double-checked the date format and I couldn't find the issue. I used `readxl::read_excel` (reading date data as 'date', 'text' and 'numeric', I tested all the ways) for reading the data, then I changed it to base `read.csv` and all date issues disappeared. I'm posting here just if any other user faces the same problem.

I have no clue what happened, both I checked the output of both ways and it's the same

**Comment by Yuanchao-Xu** [comment]
@aldotapia Hi, can you provide a piece of your data so that I can have a look?

**Comment by afifatalukder** [comment]
Having the same problem. Badly need help. @Yuanchao-Xu looking for your kind response

**Comment by rp-jpg** [comment]
i am also having the same issue please help.  @Yuanchao-Xu
